Allow shared reqwest client configuration
tag1consulting/goose pull request #357
Opened 2021-09-01 09:24 UTC by finnefloyd

From Reqwest official documentation:

> The Client holds a connection pool internally, so it is advised that you create one and reuse it.
    You do not have to wrap the Client it in an Rc or Arc to reuse it, because it already uses an Arc internally.

This PR, use a shared reqwest client among all GooseUser and allow the user the configure the global client.

2021-09-02 15:35 UTC, jeremyandrews commented
Merge conflict needs to be resolved

2021-09-02 15:38 UTC, jeremyandrews commented
It's unclear to me if this will result in cookies and headers being shared between all `GooseUser`s, which would be undesirable.

2021-09-05 15:54 UTC, finnefloyd commented
> It's unclear to me if this will result in cookies and headers being shared between all GooseUsers, which would be undesirable.

Goose point, I did not think about it and I'm not using cookies in my current load tests, I didn't detect it. I moved the cookies handling to the `GooseUser` so we can shared the connection pool

2021-09-06 05:53 UTC, jeremyandrews commented
This addresses cookies, but there’s still a problem from shared headers. For example, if using http header authentication, with this PR once one GooseUser logs in all would be.

2021-09-06 06:03 UTC, jeremyandrews commented
For example, as documented here it's currently possible to set different headers with different GooseUsers, and this is required functionality for many load tests:
https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#example-18

2021-09-06 06:28 UTC, jeremyandrews commented
This example will also need to be updated to show how to set custom cookies:
https://docs.rs/goose/*/goose/goose/struct.GooseUser.html#example-19

2021-09-06 08:42 UTC, finnefloyd commented
I added support for default headers and custom cookies to the GooseUser.

2021-09-07 07:21 UTC, jeremyandrews requested changes
What is the intent of this change? Why are you trying to share a single Client pool?

Goose intentionally maintains a unique client-per-`GooseUser`, with the intent of better simulating independent users -- sharing a Client pool adds complexity and I worry this could result in unintended bugs. It also further ties Goose to the inner-workings of Reqwest, whereas the goal is to enhance Goose to support other client libraries and be less-tied to specific Reqwest implementation details.

I imagine there could be reduced memory requirements through this change, and possibly better startup-performance? (I am on the road an unable to test/validate this, which seems to be the only potential advantage of this added complexity?)

At this time I do not see sufficient value in merging this PR.

2021-09-07 07:21 UTC, jeremyandrews commented on src/goose.rs
> +    /// Default headers can be manually set to each [`GooseUser`](./goose/struct.GooseUser.html).
`set on` instead of `set to`

2021-09-07 07:21 UTC, jeremyandrews commented on src/goose.rs
> +    /// The headers will automatically been added to each request made by the [`GooseUser`](./goose/struct.GooseUser.html).
`be added` instead of `been added`

2021-09-07 07:21 UTC, jeremyandrews commented on src/goose.rs
> +    /// Default headers doesn't overwrite already appended headers.
`do not` (or `don't`) instead of `doesn't`

2021-09-07 07:21 UTC, jeremyandrews commented on src/lib.rs
> +        self.client = client_builder.cookie_store(false).build()?;
This seems to make it impossible to enable the `cookie_store` -- if that's the intent it needs to be documented.

2021-10-08 19:16 UTC, LionsAd commented
@finnefloyd Thanks for all your contributions so far!

I share Jeremy's sentiment that I would like to understand the motivation of the change a little bit more, before considering this PR.

2022-12-20 09:53 UTC, netom commented
> @finnefloyd Thanks for all your contributions so far!
> 
> I share Jeremy's sentiment that I would like to understand the motivation of the change a little bit more, before considering this PR.

I used Goose recently, and I needed to create thoudands of users. Starting Goose took about thirty seconds. The tests themselves were not terribly long, so the startup time was significant.

I solved this by monkey-patching goose to use a single reqwest client. (Cookies and headers weren't an issue for me.) This way the statup time disappeared.

I know this is a corner case, but IMHO worth implementing client sharing.

The general argument would be "because it's just more resource efficient".

2025-08-25 11:13 UTC, jeremyandrews commented
This should be addressed with https://github.com/tag1consulting/goose/pull/578

2025-08-25 11:13 UTC, closed without merging