disable default chrono features
tag1consulting/goose pull request #559
Opened 2023-08-25 15:54 UTC by jeremyandrews

- fixes https://github.com/tag1consulting/goose/issues/558 
 - only enable required features from `chrono`, addressing https://rustsec.org/advisories/RUSTSEC-2020-0071

> A possible workaround for crates affected through the transitive dependency in chrono, is to avoid using the default oldtime feature dependency of the chrono crate by disabling its default-features and manually specifying the required features instead.

2023-08-26 07:48 UTC, jeremyandrews commented
@LionsAd I don't see the need to declare this a security release, worst-case it seems anther user on the server running the load test could cause the load test to segfault. In general, it would be unwise to run a load test on a shared server anyway. If you agree, I'll go ahead and merge as-is.

2023-08-28 07:11 UTC, slashrsm requested changes

2023-08-28 07:11 UTC, slashrsm commented on CHANGELOG.md
> + - []() disable unnecessary features in chronos, avoid potential segfault in time crate: https://rustsec.org/advisories/RUSTSEC-2020-0071
Link missing.

2023-08-28 07:17 UTC, jeremyandrews commented on CHANGELOG.md
> + - []() disable unnecessary features in chronos, avoid potential segfault in time crate: https://rustsec.org/advisories/RUSTSEC-2020-0071
Oh my! Thank you :)

2023-08-28 07:27 UTC, slashrsm approved these changes

2023-08-28 07:28 UTC, merged